application: mericas-1089
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.app

- url: /
  script: models.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest